name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: x64
      - name: black
        uses: psf/black@stable
        with:
          options: '--verbose'
          src: './scripts'
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit
        with:
          commit_message: Auto-format python code
      - name: run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: 'flake8' # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check all scripts have a script.py file
        run: |
          dirs_with_missing_script=$(find scripts -maxdepth 2 -mindepth 2 -type d \! -exec test -f '{}'/script.py \; -print)
          if [[ $dirs_with_missing_script ]]; then
            echo "setFailed:: missing 'script.py' in ${dirs_with_missing_scripts//$'\n'/ }"
          fi
